version: "3"

services:
  test:
    build:
      context: .
    volumes:
      - "./test/screenshots/standards/:/mapgl-ruler/test/screenshots/standards"
    command: ['npm', 'test']

  screenshot-update:
    build:
      context: .
    volumes:
      - "./test/screenshots/standards/:/mapgl-ruler/test/screenshots/standards"
    command: ['npm', 'run', 'test:screenshots:update']
